"use strict";
exports.__esModule = true;
var linkedList_1 = require("./linkedList");
var linkedList = new linkedList_1.LinkedList();
linkedList.insertFirstNode(1);
linkedList.insertFirstNode(2);
linkedList.insertFirstNode(3);
linkedList.insertFirstNode(6);
linkedList.insertLastNode(9);
console.log(linkedList.getSize());
console.log(linkedList.readList());
